#配置服务器信息
server:
  port: 8003
  #context-path: /study 配置根目录
  context-path: /


#数据库信息配置
spring:
  application:
    name: springcloud-dept  #应用名称
  datasource:
    url: jdbc:mysql://localhost:3306/study03?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5           #数据库连接池的最小维持连接数
      initial-size: 5       #初始化连接数
      max-total: 5          #最大连接数
      max-wait-millis: 200  #等待连接获取的最大超时时间

    #druid连接池配置
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    # 配置监控统计拦截的filters,去掉监控界面sql无法统计，‘wall’用于防火墙
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    userGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    cache-enabled: true #开启二级缓存
#客户端注册进eureka服务列表
eureka:
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    #服务实例名称修改
    instance-id: springcloud-dept8003
    #访问路径显示IP地址
    prefer-ip-address: true

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
